# Overview

N-dimensional arrays in Python.

In [1]:
import numpy as np

# Importing Specific Functions

In [2]:
from numpy import random
random.randint( 4 )

0

In [3]:
from numpy.random import randint
randint( 22 )

10

# Creating From a List

In [4]:
my_list = [ 1, 2, 3 ]
array = np.array( my_list )
print( array )
print( type( array ) )

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
my_mat = [ [ 1, 2, 3 ], [ 4, 5, 6 ] ]
matrix = np.array( my_mat )
print( matrix )
print( type( matrix ) )

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


# Indexing / Slicing

You can indexing into one dimension arrays using a single digit or with the range operator.

In [6]:
array = np.arange( 0, 20 )

print( array[ 5 ] )
print( array[ 5:10 ] )
print( array[ 18: ] )
print( array[ :12 ] )
print( array[ :-12 ] )
print( array[ :-12:5 ] )
print( array[ : ] )
print( array[ ::-1 ] )

5
[5 6 7 8 9]
[18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[0 1 2 3 4 5 6 7]
[0 5]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


You can index into an 2-dimensional array by row first, then by column, using a comma as a separator. Indexing is 0-based for both the row and the column.

In [7]:
# Indexing an n-dimensional matrix
array = np.arange( 0, 20 )
matrix = np.reshape( array, ( 5, 4 ) )

# Command / Single bracket notation
print( matrix[ 1, 2 ] )

# Double bracket notation
print( matrix[ 1 ][ 2 ] )

6
6


In [8]:
# Slicing an n-dimensional matrix
array = np.arange( 0, 20 )
matrix = np.reshape( array, ( 5, 4 ) )

print( matrix )
print()
print( matrix[ 1:3, 2:4 ])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

[[ 6  7]
 [10 11]]


# Mutable Slicing

You can slice an ndarray, and it will return a slice that has a reference to the original array. So, if you update the slice, you'll also update the original array. This makes it easier to do performant array and matrix operations without having to allocate more memory for new arrays. 

In [9]:
array = np.array( [ 1, 2, 3, 4, 5, 6 ] )

slice = array[ 2:5 ]

print( "Array:", array )
print( "Slice:", slice )

slice[ 0 ] = 52
print( "slice[ 0 ] = 52")

print( "Slice:", slice )
print( "Array:", array )

Array: [1 2 3 4 5 6]
Slice: [3 4 5]
slice[ 0 ] = 52
Slice: [52  4  5]
Array: [ 1  2 52  4  5  6]


# Assignment & Broadcasting

You can assign a single value in an array

In [10]:
array = np.arange( 0, 20 )

array[ 5 ] = 333
print( array[ 5 ] )

333


You can broadcast (assign to multiple values)

In [11]:
array = np.arange( 0, 20 )

array[ 5:10 ] = 333
print( array[ 1:15 ] )

[  1   2   3   4 333 333 333 333 333  10  11  12  13  14]


# Casting

Numpy arrays can only have a single data type so when you provide multiple data types, the items in the array will get converted into the lowest common denominator.

If integers and floats are mixed, everything becomes a float.

In [12]:
list = [ 1, 2, 3, 5.5 ]
np.array( list )

array([1. , 2. , 3. , 5.5])

If numerics and strings are mixed, everything becomes a string.

In [13]:
list = [ 1, 2, 3, 5.5, 'string' ]
np.array( list )

array(['1', '2', '3', '5.5', 'string'], dtype='<U32')

# Conditonal Selection

In [14]:
arr = np.arange( 10 )
print( arr )

is_greater_than_10 = arr > 5
print( is_greater_than_10 )

arr2 = arr[ is_greater_than_10 ]
print( arr2 )

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[6 7 8 9]


# N-Dimensional Matrices

The matrix can be n-dimensional. For example, you can make a three-dimensional array by adjusting the tuple provided as the second argument.

In [15]:
array = np.arange( 0, 27 )
matrix = np.reshape( array, ( 3, 3, 3 ) )

print( matrix )

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [16]:
matrix[1,1,1]

13

# Scalar Operations

### Scalar Addition

In [17]:
arr = np.random.randint( 5, 10, ( 5, 5) )

print( arr + 140 )

[[146 147 146 148 146]
 [145 147 146 145 148]
 [147 147 148 145 145]
 [149 147 148 147 149]
 [147 149 146 148 146]]


### Scalar Subtraction

In [18]:
arr = np.random.randint( 5, 10, ( 5, 5) )

print( arr - 22 )

[[-16 -14 -16 -15 -13]
 [-17 -17 -13 -15 -13]
 [-16 -15 -16 -14 -15]
 [-14 -17 -17 -13 -14]
 [-16 -17 -17 -13 -15]]


### Scalar Multiplication

In [19]:
scalar = 5
array = np.arange( 0, 5 )
array2 = np.ones( ( 5, 5 ) )
matrix = np.matrix( np.ones( ( 5, 5 ) ) )

print( type( scalar * array ) )
print( scalar * array )
print()
print( type( scalar * array2 ) )
print( scalar * array2 )
print()
print( type( scalar * matrix ) )
print( scalar * matrix )

<class 'numpy.ndarray'>
[ 0  5 10 15 20]

<class 'numpy.ndarray'>
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]

<class 'numpy.matrix'>
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


### Scalar Division

In [20]:
arr = np.random.randint( 5, 10, ( 5, 5) )
print( arr / 10 )

[[0.9 0.8 0.7 0.6 0.5]
 [0.7 0.6 0.7 0.9 0.6]
 [0.9 0.9 0.8 0.9 0.9]
 [0.5 0.9 0.9 0.5 0.5]
 [0.8 0.5 0.6 0.7 0.7]]


In [21]:
arr = np.arange( 20 )
print( 1 / arr) # warning because first entry is 0

[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111 0.1        0.09090909
 0.08333333 0.07692308 0.07142857 0.06666667 0.0625     0.05882353
 0.05555556 0.05263158]


<ipython-input-21-81f59a7f5e87>:2: RuntimeWarning: divide by zero encountered in true_divide
  print( 1 / arr) # warning because first entry is 0


In [22]:
arr = np.arange( 20 )
print( arr / 0 ) # nan on 0/0, inf on any other int / 0

[nan inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf inf
 inf inf]


<ipython-input-22-7ac563495edb>:2: RuntimeWarning: divide by zero encountered in true_divide
  print( arr / 0 ) # nan on 0/0, inf on any other int / 0
<ipython-input-22-7ac563495edb>:2: RuntimeWarning: invalid value encountered in true_divide
  print( arr / 0 ) # nan on 0/0, inf on any other int / 0


### Scalar Power

In [56]:
arr = np.arange( 20 )
print( arr ** 2 )

[  0   1   4   9  16  25  36  49  64  81 100 121 144 169 196 225 256 289
 324 361]


### Square Root

In [61]:
arr = np.arange( 20 ) ** 2
print( np.sqrt( arr ) )

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]


### Exponential

In [64]:
arr = np.exp( np.arange( 20 ) )
arr

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04,
       1.62754791e+05, 4.42413392e+05, 1.20260428e+06, 3.26901737e+06,
       8.88611052e+06, 2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

# Matrix Operations

### Matrix Addition

In [24]:
arr = np.random.randint( 5, 10, ( 5, 5) )
arr2 = np.random.randint( 5, 10, ( 5, 5) )

print( arr + arr2 )

[[14 13 15 15 14]
 [14 14 17 15 12]
 [13 13 15 13 13]
 [14 13 18 13 14]
 [13 11 15 15 13]]


### Matrix Subtraction

In [25]:
arr = np.random.randint( 5, 10, ( 5, 5) )
arr2 = np.random.randint( 5, 10, ( 5, 5) )

print( arr - arr2 )

[[ 1  1 -4  3 -1]
 [ 1 -1  1 -2  1]
 [-1  1 -3  0  2]
 [-2  3 -1  3 -1]
 [-2 -1  0  1  0]]


### Row Vector Multiplication

In [26]:
array = np.arange( 0, 5 )
array2 = np.ones( ( 5, 5 ) )
matrix = np.matrix( np.ones( ( 5, 5 ) ) )

print( type( array * array ) )
print( array * array )
print()
print( type( array * array2 ) )
print( array * array2 )
print()
print( type( array * matrix ) )
print( array * matrix )

<class 'numpy.ndarray'>
[ 0  1  4  9 16]

<class 'numpy.ndarray'>
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

<class 'numpy.matrix'>
[[10. 10. 10. 10. 10.]]


### Column Vector Multiplication

In [27]:
array = np.arange( 0, 5 )
array2 = np.ones( ( 5, 5 ) )
matrix = np.matrix( np.ones( ( 5, 5 ) ) )
vector = np.reshape( np.arange( 2, 7 ), ( 5, 1 ), order='F' )

print( type( vector ) )
print( vector )
print()
print( type( array * vector ) )
print( array * vector )
print()
print( type( array2 * vector ) )
print( array2 * vector )
print()
print( type( matrix * vector ) )
print( matrix * vector )

<class 'numpy.ndarray'>
[[2]
 [3]
 [4]
 [5]
 [6]]

<class 'numpy.ndarray'>
[[ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]
 [ 0  5 10 15 20]
 [ 0  6 12 18 24]]

<class 'numpy.ndarray'>
[[2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]]

<class 'numpy.matrix'>
[[20.]
 [20.]
 [20.]
 [20.]
 [20.]]


### Matrix Multiplication With Arrays

You can use `matrix()` to create a NumPy matrix, but it's arguably better to use array:

> However, you should really use array instead of matrix. matrix objects have all sorts of horrible incompatibilities with regular ndarrays. With ndarrays, you can just use * for elementwise multiplication:

`a * b`

> If you're on Python 3.5+, you don't even lose the ability to perform matrix multiplication with an operator, because @ does matrix multiplication now:

`a @ b  # matrix multiplication`

References:
- [How to get element-wise matrix multiplication (Hadamard product) in numpy?](https://stackoverflow.com/questions/40034993/how-to-get-element-wise-matrix-multiplication-hadamard-product-in-numpy)

In [28]:
array1 = np.ones( ( 5, 5 ) )
vector = np.reshape( np.arange( 2, 7 ), ( 5, 1 ), order='F' )

print( array1 @ vector )

[[20.]
 [20.]
 [20.]
 [20.]
 [20.]]


# Numpy Functions

References:
- [Numpy Docs - Universal functions (ufunc)](https://numpy.org/doc/stable/reference/ufuncs.html)

### arange()

In [71]:
# Length (starting at 0)
array = np.arange( 20 )
print( array )
print( type( array ) )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [72]:
# With start / length
array = np.arange( 5, 20 )
print( array )

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [31]:
# Skipping
array = np.arange( 0, 100, 13 )
print( array )

[ 0 13 26 39 52 65 78 91]


### argmax() / argmin()

Find the index locaiton of the maximum or minimum value.

In [32]:
# arr.argmax() / arr.argmin()
arr = np.random.randint( 0, 10, 10 )
print( 'location of min value:', arr.argmin() )
print( 'location of max value:', arr.argmax() )

location of min value: 8
location of max value: 5


In [33]:
# np.argmax() / np.argmin()
arr = np.random.randint( 0, 10, 10 )
print( 'location of min value:', np.argmin( arr ) )
print( 'location of max value:', np.argmax( arr ) )

location of min value: 9
location of max value: 8


### array()

You can convert a list into an array using `array()`. 

In [34]:
array = np.array( [ 1, 2, 3, 4, 5, 6 ] )
print( array )

[1 2 3 4 5 6]


In [35]:
array = np.array( [ [ 1, 2, 3 ], [ 4, 5, 6 ] ] )
print( array )

[[1 2 3]
 [4 5 6]]


### copy()

In [36]:
arr = np.arange( 5 )
arr_copy = arr.copy()

# Broadcast update the array to prove that the copy isn't getting updated
arr[:] = 999

print(arr)
print(arr_copy)

[999 999 999 999 999]
[0 1 2 3 4]


### dot()

Dot-product of two arrays.

References:
- [NumPy v1.19 docs - numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

In [37]:
matrix = np.reshape( np.arange( 1, 21 ), ( 5, 4 ) )
vector = np.reshape( np.arange( 2, 6 ), ( 4, 1 ), order='F' )

result = matrix.dot( vector )

print( matrix )
print( vector )
print( result )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[2]
 [3]
 [4]
 [5]]
[[ 40]
 [ 96]
 [152]
 [208]
 [264]]


### dtype()

Get the data type of the entries in the array

In [38]:
arr = np.arange( 20 )
print( arr.dtype )

int64


### eye()

`eye( n )`

Returns an identity matrix of size n x n.

In [39]:
np.eye( 4 )

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### linspace()

`linspace( x, y, z )`

Gives evenly spaced array of size z between x and y. 

In [40]:
np.linspace( 0, 5, 10 )

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### matmul()

In [41]:
matrix = np.reshape( np.arange( 1, 21 ), ( 5, 4 ) )
vector = np.reshape( np.arange( 2, 6 ), ( 4, 1 ), order='F' )

result = np.matmul( matrix, vector )

print( matrix )
print( vector )
print( result )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[2]
 [3]
 [4]
 [5]]
[[ 40]
 [ 96]
 [152]
 [208]
 [264]]


### matrix()

In [42]:
a = np.matrix( [ [ 1, 2 ], [ 3, 4 ] ] )

print( a )
print( type( a ) )

[[1 2]
 [3 4]]
<class 'numpy.matrix'>


### max() / min()

Maximum and minimum value in the array.

In [43]:
# array.max() / array.min()
arr = np.random.randint( 0, 10, 10 )
print( 'max: ', arr.max() )
print( 'min: ', arr.min() )

max:  8
min:  0


In [44]:
# np.max() / np.min()
arr = np.random.randint( 0, 10, 10 )
print( 'max: ', np.max( arr ) )
print( 'min: ', np.min( arr ) )

max:  9
min:  1


### ones()

In [45]:
array = np.ones( 5 )
print( array )

[1. 1. 1. 1. 1.]


In [46]:
matrix = np.ones( (5, 3 ) )
print( matrix )

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### random()

Many options such as:
- `np.random.rand`
- `np.random.binomial`
- `np.random.chisquare`
- `np.random.poisson`
- etc

In [47]:
# From a uniform distribution
print( np.random.rand() )
print( np.random.rand( 4 ) )
print( np.random.rand( 2, 2 ) )

0.9814988046186107
[0.20945891 0.75276933 0.92922133 0.70452765]
[[0.64200981 0.47129809]
 [0.27439368 0.38802238]]


In [48]:
# From a normal / gaussian distribution
print( np.random.randn() )
print( np.random.randn( 4 ) )
print( np.random.randn( 2, 2 ) )

0.16518057414877668
[ 1.24601088  1.92014995 -1.11444348 -0.95773798]
[[-0.34364908  0.89897033]
 [-0.68633358 -0.41506797]]


In [49]:
# Random integers in a range (lowest inclusive, highest exclusive)
print( np.random.randint( 2, 20 ) )
print( np.random.randint( 2, 20, 4 ) )
print( np.random.randint( 2, 20, ( 2, 2 ) ) )

9
[16 18  2 19]
[[16 13]
 [10  2]]


### reshape()

The reshape function will convert an array into an array of arrays, thereby making it a matrix.

The reshape function will populate rows first and then columns, by default.

In [50]:
array = np.arange( 0, 20 )
matrix = np.reshape( array, ( 5, 4 ) )
print( matrix )
print( type( matrix ) )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
<class 'numpy.ndarray'>


The default value is the same as specifying `order='C'`, where `C` refers to the C programming language. 

In [51]:
array = np.arange( 0, 20 )
matrix = np.reshape( array, ( 5, 4 ), order='C' )
print( matrix )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


You can have it populate columns first using `order='F'`, where `F` refers to the Fortran programming language.

In [52]:
array = np.arange( 0, 20 )
matrix = np.reshape( array, ( 5, 4 ), order='F' )
print( matrix )

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


### shape

In [53]:
arr = np.arange( 20 )
arr2 = arr.reshape( ( 5, 4 ) )
print( arr.shape )
print( arr2.shape )

(20,)
(5, 4)


### sum()

In [84]:
arr = np.arange( 20 ).reshape(4,5)

print( arr )

# Sum of all elements
print( arr.sum() )
print( np.sum( arr ) )

# Sum of all columns
print( np.sum( arr, axis=0 ) )

# Sum of all rows
print( np.sum( arr, axis=1 ) )

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
190
190
[30 34 38 42 46]
[10 35 60 85]


### sin()

In [69]:
arr = np.arange( 20 )

np.sin( arr )

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

### std()

Standard deviation

In [157]:
arr = np.random.randn( 200 )
arr.std()

1.0321098366427914

### var()

Returns the variance of the array elements, along given axis.

In [161]:
arr = np.random.randn( 100 ).reshape( 10, 10 )

# All numbers
arr.var()

# Columns
arr.var( axis=0 )

# Rows
arr.var( axis=1 )

array([0.90405912, 0.41031914, 0.98256713, 1.15151322, 0.78867115,
       1.64332408, 0.65619719, 1.24468939, 0.75736   , 1.72230368])

### zeros()

In [54]:
array = np.zeros( 5 )
print( array )

[0. 0. 0. 0. 0.]


In [55]:
matrix = np.zeros( ( 5, 3 ) )
print( matrix )

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
