# Overview

N-dimensional arrays in Python.

In [1]:
import numpy as np

# Basics

### Indexing

You can index into an array by row first, then by column, using a comma as a separator. Indexing is 0-based for both the row and the column.

In [2]:
array = np.arange( 0, 20 )
matrix = np.reshape( array, ( 5, 4 ) )
matrix[1,2]

6

### Mutable Slicing

You can slice an ndarray, and it will return a slice that has a reference to the original array. So, if you update the slice, you'll also update the original array. This makes it easier to do performant array and matrix operations without having to allocate more memory for new arrays. 

In [17]:
array = np.array( [ 1, 2, 3, 4, 5, 6 ] )

slice = array[ 2:5 ]

print( "Array:", array )
print( "Slice:", slice )

slice[ 0 ] = 52
print( "slice[ 0 ] = 52")

print( "Slice:", slice )
print( "Array:", array )

Array: [1 2 3 4 5 6]
Slice: [3 4 5]
slice[ 0 ] = 52
Slice: [52  4  5]
Array: [ 1  2 52  4  5  6]


### Casting

Numpy arrays can only have a single data type so when you provide multiple data types, the arrays will get converted into the lowest common denominator.

If integers and floats are mixed, everything becomes a float.

In [18]:
list = [ 1, 2, 3, 5.5 ]
np.array( list )

array([1. , 2. , 3. , 5.5])

If numerics and strings are mixed, everything becomes a string.

In [19]:
list = [ 1, 2, 3, 5.5, 'string' ]
np.array( list )

array(['1', '2', '3', '5.5', 'string'], dtype='<U32')

### N-Dimensional Matrix

The matrix can be n-dimensional. For example, you can make a three-dimensional array by adjusting the tuple provided as the second argument.

In [4]:
array = np.arange( 0, 27 )
matrix = np.reshape( array, ( 3, 3, 3 ) )

print( matrix )

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [5]:
matrix[1,1,1]

13

# Operations

### Scalar Multiplication

In [84]:
scalar = 5
array = np.arange( 0, 5 )
array2 = np.ones( ( 5, 5 ) )
matrix = np.matrix( np.ones( ( 5, 5 ) ) )

print( type( scalar * array ) )
print( scalar * array )
print()
print( type( scalar * array2 ) )
print( scalar * array2 )
print()
print( type( scalar * matrix ) )
print( scalar * matrix )

<class 'numpy.ndarray'>
[ 0  5 10 15 20]

<class 'numpy.ndarray'>
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]

<class 'numpy.matrix'>
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


### Row Vector Multiplication

In [86]:
array = np.arange( 0, 5 )
array2 = np.ones( ( 5, 5 ) )
matrix = np.matrix( np.ones( ( 5, 5 ) ) )

print( type( array * array ) )
print( array * array )
print()
print( type( array * array2 ) )
print( array * array2 )
print()
print( type( array * matrix ) )
print( array * matrix )

<class 'numpy.ndarray'>
[ 0  1  4  9 16]

<class 'numpy.ndarray'>
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]

<class 'numpy.matrix'>
[[10. 10. 10. 10. 10.]]


### Column Vector Multiplication

In [82]:
array = np.arange( 0, 5 )
array2 = np.ones( ( 5, 5 ) )
matrix = np.matrix( np.ones( ( 5, 5 ) ) )
vector = np.reshape( np.arange( 2, 7 ), ( 5, 1 ), order='F' )

print( type( vector ) )
print( vector )
print()
print( type( array * vector ) )
print( array * vector )
print()
print( type( array2 * vector ) )
print( array2 * vector )
print()
print( type( matrix * vector ) )
print( matrix * vector )

<class 'numpy.ndarray'>
[[2]
 [3]
 [4]
 [5]
 [6]]

<class 'numpy.ndarray'>
[[ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]
 [ 0  5 10 15 20]
 [ 0  6 12 18 24]]

<class 'numpy.ndarray'>
[[2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]
 [5. 5. 5. 5. 5.]
 [6. 6. 6. 6. 6.]]

<class 'numpy.matrix'>
[[20.]
 [20.]
 [20.]
 [20.]
 [20.]]


### Matrix Multiplication With Arrays

You can use `matrix()` to create a NumPy matrix, but it's arguably better to use array:

> However, you should really use array instead of matrix. matrix objects have all sorts of horrible incompatibilities with regular ndarrays. With ndarrays, you can just use * for elementwise multiplication:

`a * b`

> If you're on Python 3.5+, you don't even lose the ability to perform matrix multiplication with an operator, because @ does matrix multiplication now:

`a @ b  # matrix multiplication`

References:
- [How to get element-wise matrix multiplication (Hadamard product) in numpy?](https://stackoverflow.com/questions/40034993/how-to-get-element-wise-matrix-multiplication-hadamard-product-in-numpy)

In [89]:
array1 = np.ones( ( 5, 5 ) )
vector = np.reshape( np.arange( 2, 7 ), ( 5, 1 ), order='F' )

print( array1 @ vector )

[[20.]
 [20.]
 [20.]
 [20.]
 [20.]]


# Functions

### arange()

In [6]:
array = np.arange( 0, 20 )
print( array )
print( type( array ) )

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


### array()

You can convert a list into an array using `array()`. 

In [21]:
array = np.array( [ 1, 2, 3, 4, 5, 6 ] )
print( array )

[1 2 3 4 5 6]


In [8]:
array = np.array( [ [ 1, 2, 3 ], [ 4, 5, 6 ] ] )
print( array )

[[1 2 3]
 [4 5 6]]


### dot()

Dot-product of two arrays.

References:
- [NumPy v1.19 docs - numpy.dot](https://numpy.org/doc/stable/reference/generated/numpy.dot.html)

In [53]:
matrix = np.reshape( np.arange( 1, 21 ), ( 5, 4 ) )
vector = np.reshape( np.arange( 2, 6 ), ( 4, 1 ), order='F' )

result = matrix.dot( vector )

print( matrix )
print( vector )
print( result )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[2]
 [3]
 [4]
 [5]]
[[ 40]
 [ 96]
 [152]
 [208]
 [264]]


### matmul()

In [55]:
matrix = np.reshape( np.arange( 1, 21 ), ( 5, 4 ) )
vector = np.reshape( np.arange( 2, 6 ), ( 4, 1 ), order='F' )

result = np.matmul( matrix, vector )

print( matrix )
print( vector )
print( result )

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
[[2]
 [3]
 [4]
 [5]]
[[ 40]
 [ 96]
 [152]
 [208]
 [264]]


### matrix()

In [66]:
a = np.matrix( [ [ 1, 2 ], [ 3, 4 ] ] )

print( a )
print( type( a ) )

[[1 2]
 [3 4]]
<class 'numpy.matrix'>


### ones()

In [57]:
array = np.ones( 5 )
print( array )

[1. 1. 1. 1. 1.]


In [60]:
matrix = np.ones( (5, 3 ) )
print( matrix )

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### reshape()

The reshape function will convert an array into an array of arrays, thereby making it a matrix.

The reshape function will populate rows first and then columns, by default.

In [9]:
array = np.arange( 0, 20 )
matrix = np.reshape( array, ( 5, 4 ) )
print( matrix )
print( type( matrix ) )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
<class 'numpy.ndarray'>


The default value is the same as specifying `order='C'`, where `C` refers to the C programming language. 

In [10]:
array = np.arange( 0, 20 )
matrix = np.reshape( array, ( 5, 4 ), order='C' )
print( matrix )

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


You can have it populate columns first using `order='F'`, where `F` refers to the Fortran programming language.

In [11]:
array = np.arange( 0, 20 )
matrix = np.reshape( array, ( 5, 4 ), order='F' )
print( matrix )

[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


### zeros()

In [61]:
array = np.zeros( 5 )
print( array )

[0. 0. 0. 0. 0.]


In [63]:
matrix = np.zeros( ( 5, 3 ) )
print( matrix )

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
